#!/usr/bin/env python3
"""Build pipeline for tinyvm.

Produces three artifacts in ./build/:
  1. macrovm.bin           -- run-min.luau compiled to our bytecode format.
                              This is the "macro-VM" interpreter that the
                              micro-VM (src/tinyvm.luau) executes to obtain
                              the full-featured Luau interpreter.
  2. macrovm-module.luau   -- A Luau module that returns the macro-VM bytes
                              as a string. Convenient for `require()` from
                              consumer code.
  3. tinyvm-bundled.luau   -- Self-contained: the micro-VM source + the
                              macro-VM bytecode embedded inline. Returns a
                              function f(userBytecode, env, label, ...) that
                              runs user bytecode end-to-end. Use this when
                              `require()` is impractical.

Usage:
    python tools/build.py            # builds all three
    python tools/build.py --bundle   # only the bundled file
"""
from __future__ import annotations
import sys, pathlib, subprocess, argparse

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
BUILD = ROOT / "build"
COMPILER = ROOT / "tools" / "compiler.py"

def _hex_lit(data: bytes) -> str:
    return "".join(f"\\x{b:02x}" for b in data)

def _lua_string_literal(data: bytes) -> str:
    """Encode bytes as a Lua double-quoted string with \\xNN escapes for non-printable."""
    out = ['"']
    for b in data:
        if b == 0x22: out.append('\\"')
        elif b == 0x5c: out.append('\\\\')
        elif 32 <= b < 127: out.append(chr(b))
        elif b == 0x0a: out.append('\\n')
        elif b == 0x09: out.append('\\t')
        elif b == 0x0d: out.append('\\r')
        else: out.append(f"\\x{b:02x}")
    out.append('"')
    return "".join(out)

def build_macro_bin() -> bytes:
    BUILD.mkdir(exist_ok=True)
    out = BUILD / "macrovm.bin"
    subprocess.check_call([sys.executable, str(COMPILER), str(SRC/"macrovm.luau"), str(out)])
    data = out.read_bytes()
    print(f"  macrovm.bin: {len(data)} bytes")
    return data

def write_macro_module(macro_bytes: bytes) -> pathlib.Path:
    out = BUILD / "macrovm-module.luau"
    out.write_text(
        "--!nocheck\n"
        "-- Auto-generated by tools/build.py. Returns the macro-VM bytecode.\n"
        f"return {_lua_string_literal(macro_bytes)}\n",
        encoding="utf-8",
    )
    print(f"  macrovm-module.luau: {out.stat().st_size} bytes")
    return out

def write_bundle(macro_bytes: bytes) -> pathlib.Path:
    micro_src = (SRC / "tinyvm.luau").read_text(encoding="utf-8")
    # Strip the trailing newline from micro_src so we can append cleanly.
    micro_src = micro_src.rstrip("\n")
    # The micro-VM is an expression that evaluates to a function f(macro, ...).
    # We wrap it so the bundle exposes f2(user, env, label, ...) = f(macro, user, env, label, ...).
    out = BUILD / "tinyvm-bundled.luau"
    out.write_text(
        "--!nocheck\n"
        "-- Self-contained tinyvm bundle: micro-VM + macro-VM bytecode embedded.\n"
        "-- Usage:\n"
        "--     local play = require(\"./tinyvm-bundled\")\n"
        "--     local result = play(userBytecode, env, label, ...)\n"
        f"local _macro = {_lua_string_literal(macro_bytes)}\n"
        "local _mvm = (function()\n"
        f"{micro_src}\n"
        "end)()\n"
        "return function(...) return _mvm(_macro, ...) end\n",
        encoding="utf-8",
    )
    print(f"  tinyvm-bundled.luau: {out.stat().st_size} bytes")
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", action="store_true", help="only emit the bundled file")
    args = ap.parse_args()

    print("Building tinyvm artifacts...")
    macro = build_macro_bin()
    if not args.bundle:
        write_macro_module(macro)
    write_bundle(macro)
    print()
    print("Done. Outputs in ./build/")
    print()
    print(f"src/tinyvm.luau (micro-VM source):  {(SRC/'tinyvm.luau').stat().st_size} bytes")
    print(f"src/macrovm.luau (macro-VM source): {(SRC/'macrovm.luau').stat().st_size} bytes")

if __name__ == "__main__":
    main()
